### ISSUE TITLE
is it still woking?

### ISSUE THREAD

**Issue by huahuayu** [allada/bsc-archive-snapshot#1]
hi, it's two month later since you publish this repo, is it still working? As far as I know, quicknode have bsc archive node service, start at $259 per month, a little bit expensive...

**Comment by allada** [comment]
Yes, it should be up-to-date, however the BSC has been growing quickly, so it's many more terrabytes than it was when I wrote it. You may also need to modify the script provided to download at a throttled rate because I think AWS limits the download rate.
