### ISSUE TITLE
Archive node RPC as a service?

### ISSUE THREAD

**Issue by niftyorca** [allada/bsc-archive-snapshot#10]
I need BSC archive node access with very low latency within `us-west-2`. I've already tested out a few BSC archive node providers available but none meets my requirements. I considered running my own node but the volume of requests I'm doing doesn't justify the running cost.

Is there any chance you offer your archive node as a paid service?

**Comment by allada** [comment]
Sadly no, I considered doing this, but I don't have the time to invest into maintaining a company to provide this as a service, especially given that there are a few companies already providing it.

Pretty much all the companies that offer BSC archive node as a service have contacted me directly for some advice or using the data and selling it.

To be fair, it is extremely difficult to maintain a BSC archive node, especially trying to provide it reliably as a service. There are a few projects that are near complete that will likely dramatically help and I fully expect over the next few months these companies will likely become much more stable and handle more throughput.
