### ISSUE TITLE
support xfs

### ISSUE THREAD

**Issue by flywukong** [allada/bsc-archive-snapshot#24]
can you supply xfs snapshot instead zfs? we have not used  zfs in our machine

**Comment by allada** [comment]
The snapshot data is actually a tarball. Zfs is only used in the reference/example shell script. It would be trivial to modify the shell script to use any filesystem.

Most users don't use the reference shell script in production, they usually modify it to their use cases.

**Comment by flywukong** [comment]
thanks , works well with xfs
