### ISSUE TITLE
can it run with --db.pagesize=8kb ?

### ISSUE THREAD

**Issue by flywukong** [allada/bsc-archive-snapshot#25]
the mdbx should be consistent with the config of pagesize , so this tarball is done with --db.pagesize=8kb or --db.pagesize=4kb ? if it is runned with 4kb , I am afraid that the data can not be run with flag   --db.pagesize=8kb 

PS : I did not use your script to run it ,  I have run node with below command and it works well for 10+ hours, 
./erigon --chain=bsc --datadir /server/archive --snap.keepblocks --db.pagesize=8kb

**Comment by allada** [comment]
Currently it is 4k (default), but I've been working on a new sync that is 16k that should be released in a week or so.

**Comment by flywukong** [comment]
we can also use mdbx_dump/mdbx_load tools to convert the data into 8k or 16k

**Comment by allada** [comment]
As of https://github.com/allada/bsc-archive-snapshot/commit/4d8d56ac1fe424c119ef1925f387ce24df484e31, it uses 16k blocks. This solved much of the "can't keep up with latest blocks issues".

**Comment by allada** [comment]
Currently it is 4k (default), but I've been working on a new sync that is
16k that should be released in a week or so.
