### ISSUE TITLE
Documentation issues

### ISSUE THREAD

**Issue by AndreaLanfranchi** [allada/bsc-archive-snapshot#26]
Hi ... Erigon team here.
Hope you don't mind if I point out some inaccuracies found in your readme.

> Erigon first stores the data of each wallet and contract in a flat key-value database ([mdbx](https://github.com/erthink/libmdbx) for default local db, but does support remote databases too)

Actually we don't support/implement any persistence engine other than MDBX. Though erigon is improving in building and torrent seeding snapshot files (plain binaries) their indexes and re-computed data are mantained on MDBX only. 

> The biggest problem with Erigon is that to my knowledge, it does not keep executing latest blocks as it gets them, instead it queues them up and batches them together.

That's not completely accurate.  Erigon implements a sync cycle loop which aims to follow the tip of the chain just as any other client.
Let me explain. 
Assume we're syncing a chain from scratch (archive mode):

1. Erigon starts, initializes genesis block, and starts p2p 
2. Discovered peers (as well as dial-in ones) provide erigon with the number of highest block they have (say 10M)
3. Erigon begins download headers and bodies up to block 10M (it might take hours) and when done ...
4. All stages are invoked sequentially to execute all downloaded blocks, produce state changes, recompute Merkle root, build indexes (on this very first cycle it might take days or weeks on behalf of your hw capabilities - meanwhile the chain advances)
5. At the end of first cycle Erigon goes to peers once again to check which is **now** the block number at the tip. Say the chain has advanced 500K blocks ...
6. Erigon downloads all 500k block headers and bodies and starts a new cycle which, this time, has a span of 500k blocks instead of 10M hence its duration it will be considerably less (say 2 day - YMMV). Nontheless in the mean time the chain advances ...
7. Once this second cycle has completed Erigon, once again, queries peers for the highest block of the chain at that very moment (say 10K blocks ahead) and once again downloads all block headers and bodies it does not have yet and start a new cycle ...
8. [....]
9. and on and on and on ....

It appears clear that after several cycles Erigon can reach the tip of the chain and **as long as the instance is running on HW which is capable to complete a full cycle in less time then chain block time it will process one block by one block just pretty much like other clients**. So actually a batch of blocks can be made of 1 block only and we don't stay behind the tip.

Obviously this description is over simplified and does not take into account snapshot sync, purging historical data, and, of course, whether erigon has RPCdaemon exposed to the internet to serve queries for remotes: this all have an impact on cycle's timings and db footprint. Worth to mention that ZFS compression add overhead to IO.

Hope this helps.

**Comment by flywukong** [comment]
as I test on the snapshot with archive mode on nvme disk without ZFS, the block will not fall behind too much 
<img width="1430" alt="image" src="https://user-images.githubusercontent.com/19421226/180394918-a47acf81-bde3-4369-9bb2-632d47a9d4b2.png">
<img width="210" alt="image" src="https://user-images.githubusercontent.com/19421226/180394940-acffe662-2742-4852-95b9-c7237607fd66.png">

it will keep about 10-15 blocks behind of the lastest blocks

**Comment by AndreaLanfranchi** [comment]
@flywukong please report which is the commit time of each cycle.
For that lag behind it means a cycle completes in 3 minutes or more

**Comment by flywukong** [comment]
@AndreaLanfranchi  
[INFO] [07-22|08:55:14.335] RPC Daemon notified of new headers       from=19768881 to=19768884 header sending=11.701µs log sending=312ns
[INFO] [07-22|08:55:14.335] [1/16 Headers] Waiting for headers...    from=19768884
[INFO] [07-22|08:55:14.335] [1/16 Headers] Processed                 highest inserted=19768885 age=3s
[INFO] [07-22|08:55:14.784] [6/16 Execution] Completed on            block=19768885
[INFO] [07-22|08:55:15.254] Timings (slower than 50ms)               Bodies=273ms Execution=150ms HashState=84ms IntermediateHashes=175ms StorageHistoryIndex=70ms
[INFO] [07-22|08:55:15.254] Tables                                   PlainState=170.2GB AccountChangeSet=324.2GB StorageChangeSet=1.1TB BlockTransaction=1.7TB TransactionLog=1.9TB FreeList=37.0MB ReclaimableSpace=37.0GB
[INFO] [07-22|08:55:21.950] Commit cycle                             in=6.695638362s

**Comment by flywukong** [comment]
<img width="1380" alt="image" src="https://user-images.githubusercontent.com/19421226/180411860-97a6547c-76fd-427b-828c-41ce0d5cb029.png">
<img width="284" alt="image" src="https://user-images.githubusercontent.com/19421226/180411916-9b34b4be-b03a-4f4a-9f8c-3ceff9222db0.png">

**Comment by allada** [comment]
Thanks for reviewing this @AndreaLanfranchi,

I will update the documentation in a few days. I have been hyper focused on getting the new fresh BSC node which solved much of the performance issues, and about to do a few improvements to dramatically improve download speeds.

I'll post back here once I update the documentation.

@flywukong, try using the new `.sh` file and create use the new snapshot. It is able to keep up with latest blocks now.

**Comment by leowkong** [comment]
@allada  can you tell me the update of the new snapshot ?  has it done with  pagesize 16kb? 
Actually I have  keep up with latest blocks using the old snapshot one week ago ,  with some exection error which has solved by restart or rewind.

**Comment by allada** [comment]
Yes, sorry forgot to close this. The new snapshot is done and uploaded. The way to download it has changed though, so you will need to update your download scripts accordingly. See the `sh` file for a reference.

The latest snapshot does appear to keep up.

**Comment by allada** [comment]
Thanks @AndreaLanfranchi, I have updated the documentation, if you see anything else that is wrong let me know.
