### ISSUE TITLE
No peers

### ISSUE THREAD

**Issue by FeSens** [allada/bsc-archive-snapshot#27]
Not sure if this is an issue with the downloaded files or not but...
<img width="1442" alt="image" src="https://user-images.githubusercontent.com/12564805/183324494-bf0a00b3-f6da-40e6-8a7f-c724442fe28a.png">
<img width="1447" alt="image" src="https://user-images.githubusercontent.com/12564805/183324565-b36c5145-6b40-4812-a5f5-85bd298977b5.png">

I can't get any peers... 
Any idea what can I change in the configs to get peers?
I have TCP/UDP open on ports 30303 and 42069 on my AWS security group

**Comment by allada** [comment]
It can take some time. I've seen it take over an hour to find new peers on an ip that has never bee on the network.

**Comment by FeSens** [comment]
> It can take some time. I've seen it take over an hour to find new peers on an ip that has never bee on the network.

Thanks for answer. I will wait a few more hours. 
Thanks for the snapshots. It was super fast to sync. Awsome job!

Any chance anyone is doing this on polygon?

**Comment by allada** [comment]
I'm still considering supporting polygon. Working on an agreement with a company to help support this kind of work
