### ISSUE TITLE
new snapshot decode error

### ISSUE THREAD

**Issue by leowkong** [allada/bsc-archive-snapshot#28]
I have download erigon-16k-db-latest.mdbx.zstd manually , than I use " zstd -d   erigon-16k-db-latest.mdbx.zstd " commnd to untar the tarball
<img width="1124" alt="image" src="https://user-images.githubusercontent.com/101857651/184052918-bdeb9b1e-70af-4610-a086-0a8c3a5e1e66.png">

got error:
Decoding error (36) : Corrupted block detected

**Comment by allada** [comment]
Hard to say if the upload from the seed server was bad or the download was corrupt.

There is a new snapshot uploaded every 24 hours, I suggest trying again on the new version that is uploaded.

For power users, the permissions of the bucket do allow you to download previous uploads. The bucket should hold 2-3 versions before deleting old versions. But downloading specific versions is much more complicated.
