### ISSUE TITLE
how login account

### ISSUE THREAD

**Issue by williamcarry** [allada/bsc-archive-snapshot#32]
Binance Smart Chain (BSC)
address 0x3a5f8bc460ded057cbcbec022a599642c3ca65d5
private key --redacted--

I just wanna know how login this account, my friend give it to me

**Comment by allada** [comment]
First: Never ever post your private key. By doing so allows anyone to steal your funds.

Second: this project is not related to what you are trying to do, i suggest reddit or stackoverflow.
