### ISSUE TITLE
AWS fatal error: Unable to locate credentials

### ISSUE THREAD

**Issue by Chiray1** [allada/bsc-archive-snapshot#33]
Hey,
I'm new to AWS and just tried your script. However, the download for the parlia database fails with the error Unable to locate credentials.
When I run aws s3 ls it doesn't give back The AWS Access Key Id you provided does not exist in our records. So I'm guessing this command can find the keys.
I have created a new access key and plugged it in with aws configure. Is there any more steps I need to do?

Thanks in advance!

**Comment by allada** [comment]
Are you sure that is the only file that fails? The public policy is on the entire bucket, so that would be strange.

Make sure the credentials are on root user and launch the script as root.

**Comment by cwazy2020** [comment]
I have this same issue, says credentials not found.  Running everything on sudo/root.  I tried configuring credentials as environment variables, switching to the root user and manually creating the configuration file, then running the install.  It fails both as root and via sudo as another user.  Doesn't matter, it still cannot locate the credentials no matter what I do.

aws configure list shows the proper credentials, both then I run through sudo and as a normal user.  I tried running aws configure both as sudo and as a normal user as well, nothing helped.

**Comment by allada** [comment]
Did you try `sudo aws configure`? You probably didn't run it with sudo, but are running the command with sudo.

**Comment by cwazy2020** [comment]
> Did you try `sudo aws configure`? You probably didn't run it with sudo, but are running the command with sudo.

Yes, I tried it both ways.

**Comment by allada** [comment]
I suggest bypassing sudo and use:
`sudo su root` 

Then run aws configure and the script without sudo. This will allieve any ambiguity

**Comment by cwazy2020** [comment]
> I suggest bypassing sudo and use: `sudo su root`
> 
> Then run aws configure and the script without sudo. This will allieve any ambiguity

I tried that too.  The only difference that this makes is that after it fails to find the configuration file, it continues and tries to download another file:
```
...
fatal error: Unable to locate credentials
root@ip-xxxxxxxxxx:/home/ubuntu/bsc-archive-snapshot# pzstd: -: Not overwritten.
download failed: s3://public-blockchain-snapshots/bsc/parlia-db-latest.mdbx.zstd to - [Errno 32] Broken pipe
+ true
```

**Comment by allada** [comment]
Try `aws sts get-caller-identity` if this does not work it's a problem with the aws command. AWS themselves have done pretty good documentation on trouble shooting this.

**Comment by cwazy2020** [comment]
> Try `aws sts get-caller-identity` if this does not work it's a problem with the aws command. AWS themselves have done pretty good documentation on trouble shooting this.

It's responding with the correct info on that command.  But when the aws s3 command is run by your script, for some reason it cannot find the credentials.

**Comment by allada** [comment]
Hmmm i bet the issue is the profile it creates... Try removing the `--profile xxxxxxxx` part in the script

**Comment by cwazy2020** [comment]
> Hmmm i bet the issue is the profile it creates... Try removing the `--profile xxxxxxxx` part in the script

That actually worked!  Thanks for the responses.
