### ISSUE TITLE
Problem  when calling the ListObjectsV2 operation: Access Denied

### ISSUE THREAD

**Issue by appop** [allada/bsc-archive-snapshot#34]
aws s3 sync --request-payer requester s3://public-blockchain-snapshots/bsc/erigon-snapshots-folder-latest/ /erigon/data/bsc/snapshots/
fatal error: An error occurred (AccessDenied) when calling the ListObjectsV2 operation: Access Denied

**Comment by allada** [comment]
This is most often the case when the computer you are running the command on does not have an AWS account configured.

Run `aws configure` or give the node a role.

**Comment by appop** [comment]
I ready add below permission to my account 
  "aws-portal:ModifyBilling",
                "aws-portal:ViewPaymentMethods",
                "aws-portal:ModifyAccount",
                "aws-portal:ViewAccount",
                "aws-portal:ModifyPaymentMethods",
                "aws-portal:ViewBilling",
                "aws-portal:ViewUsage"

And other permission I need ？

**Comment by allada** [comment]
You need S3 permissions, as your account will be billed for your requests.
