### ISSUE TITLE
The whole snapshot only 500GB?

### ISSUE THREAD

**Issue by appop** [allada/bsc-archive-snapshot#35]
After I run the script and complete download , this the disk usage.
tank/erigon_data                 3T  128K   39T   1% /erigon/data
tank/erigon_data/bsc             3T  256K   39T   1% /erigon/data/bsc
tank/erigon_data/bsc/parlia      3T  128K   39T   1% /erigon/data/bsc/parlia
tank/erigon_data/bsc/nodes       3T  5.4M   39T   1% /erigon/data/bsc/nodes
tank/erigon_data/bsc/snapshots   3T  563G   39T   2% /erigon/data/bsc/snapshots
tank/erigon_data/bsc/chaindata   3T  2.1G   39T   1% /erigon/data/bsc/chaindata

The data only less that 600GB?
Is my data correct?

**Comment by lcgogo** [comment]
> No, the chain data should be a few TBs. I bet the download failed. For the mdbx file.

I met the same issue, I prepare 8TB, but only 500GB is used. Do you have a guide to clean up the data and repeat again?

```shell
root@ip-10-2-1-21:/erigon# ls
create-bsc-snapshot-and-shutdown.sh  data  erigon  start_erigon_service.sh
root@ip-10-2-1-21:/erigon# du -sh
570G	.
root@ip-10-2-1-21:/erigon# du -d 1 -h
346M	./erigon
570G	./data
570G	.
```

**Comment by allada** [comment]
Recently a bunch of changes were made to the script. You likely need to use the new script.

Easiest way to reset everything is to delete the spool, it should recreate everything if it's deleted.
