### ISSUE TITLE
fatal error: An error occurred (404) when calling the HeadObject operation: Key "bsc/erigon-latest.tar.zstd" does not exist

### ISSUE THREAD

**Issue by bdonglobal** [allada/bsc-archive-snapshot#37]
When I execute this command from shell, 
aws s3 cp --request-payer=requester  "s3://public-blockchain-snapshots/bsc/erigon-latest.tar.zstd" erigon-latest.tar.zstd

the output is 
fatal error: An error occurred (404) when calling the HeadObject operation: Key "bsc/erigon-latest.tar.zstd" does not exist

**Comment by allada** [comment]
You must be using an old version of this repo's code. The location changed and there are some startup flags that need to be set when erigon starts now.

The data is no longer stored in a single tar and instead is stored in a few different files. Please use the [build_archive_node.sh](https://github.com/allada/bsc-archive-snapshot/blob/master/build_archive_node.sh) file to do the downloading.
