### ISSUE TITLE
How to use this data to deploy a bsc archive node in geth

### ISSUE THREAD

**Issue by admh** [allada/bsc-archive-snapshot#4]
Hello.I created an ec2 server with i3en.6xlarge configuration in aws according to your suggestion, downloaded all the files from s3://public-blockchain-snapshots/bsc/ and unzipped them, and got 18 data directories, and then I tried to add Block 0-4907901 as geth's data directory and started as an archive node, it can work normally, which is good, but I don't know how to make geth can use all 18 data directories at the same time, can you give me Some suggestions? thank you very much

**Comment by allada** [comment]
You'll need to run all the geth instances together and then bind them together with a proxy. `build_archive_node.sh` generally can do all the work.
