### ISSUE TITLE
How to store 30TB in AWS EBS?

### ISSUE THREAD

**Issue by lcgogo** [allada/bsc-archive-snapshot#40]
I see you metioned you store geth archive node for 30TB size.
I am interesting in how to store it in EBS, because AWS EBS gp2/gp3 only support 16TB at max. 
I know io1 or io2 can support up to 64TB but they are too expensive.

**Comment by allada** [comment]
I don't use geth any more, I use erigon, which can store a full archive node in about 6-7TB.

But to answer your question, you shard the archives into slices then use a proxy to route the requests to the node that has the blocks. See: https://github.com/allada/bsc-archive-snapshot/blob/master/ws_proxy.js for a reference on how to route requests.

**Comment by lcgogo** [comment]
Many thanks! Got it. 
Another question:
I see you suggest to use im4gn.4xlarge which is a local disk instance type. If the erigon data exceeds 7500GB
which im4gn.4xlarge provide locally, how to deal with that?

**Comment by allada** [comment]
The data is compressible. By default it uses zfs + lz4 to get about 2x compression. If you need more, use a bigger instance or raid the drives.

**Comment by lcgogo** [comment]
OK, got it
