### ISSUE TITLE
fail to start bsc archive with new snapshot

### ISSUE THREAD

**Issue by leowkong** [allada/bsc-archive-snapshot#43]
I have download the ""s3://public-blockchain-snapshots/bsc/erigon-16k-db-latest.mdbx.zstd" this week and start a bsc erigon archve node .  Then I started it with newest erigon code. I have not use "https://github.com/allada/bsc-archive-snapshot. " and the node started and download snapshot automaticly. After finished indexing , I meeted this error blow and got struck ,  the error is "No block headers to write in this log period":

then I unwind 1000 blocks and restart it :
<img width="814" alt="image" src="https://user-images.githubusercontent.com/101857651/202603058-66c0be7c-30cd-444e-8a23-7b40624985c9.png">

but it has still meeted  the same error and even got a fatal error with memory
<img width="1057" alt="image" src="https://user-images.githubusercontent.com/101857651/202603174-ca8e7ab6-ed7b-4d79-bc60-ceb47532da59.png">

**Comment by allada** [comment]
It is missing the parlia database and when it attempts to rebuild it, it runs out of memory.

Try the latest code in this repo... I changed a bunch of stuff a few days ago they will likely help.

**Comment by flywukong** [comment]
Do you mean the latest code of erigon or the bsc-archive-snapshot?

**Comment by leowkong** [comment]
try the latest code of erigon or the bsc-archive-snapshot script?  I just used aws cp to download it , without running the script @allada

**Comment by MacMemezie** [comment]
Im getting 404 key does not exist with the current endpoint in the shell script.  Im not using zfs so I just need the files but the endpoint 
"aws s3 cp --request-payer=requester s3://public-blockchain-snapshots/bsc/erigon/archive/latest/v1/snapshots/"
is giving key error.

Are we just waiting on a new update to the script?  aws s3 ls shows all the folders without the bucket so I am a little confused as to why it is giving the error

**Comment by allada** [comment]
Use `aws S3 sync`
