### ISSUE TITLE
Empty file after downloading erigon-bsc-archive 

### ISSUE THREAD

**Issue by calmbeing** [allada/bsc-archive-snapshot#44]
Hi, I tried two ways to download erigon bsc archive snapshot in this repo, but enountered two problems accordingly, can I know why?
1. I run as your this comment https://github.com/ledgerwatch/erigon/issues/5703#issuecomment-1280048804 using `aws s3 --request-payer=requester sync s3://public-blockchain-snapshots/bsc/erigon-snapshots-folder-latest/ ./snap`, but as the image below, the snap directory is empty after running this command.
 ![Pasted Graphic 2](https://user-images.githubusercontent.com/99724749/204253327-f5e95991-3285-4c61-a622-1a42afc8659e.png)

2. I used `aws s3 --request-payer=requester sync s3://public-blockchain-snapshots/bsc/erigon/archive/latest/v1/snapshots/ ./test` as the command in your .sh file, but saying like `(AccessDenied) when calling the GetObject operation: Access Denied` as below image
![Pasted Graphic 1 copy](https://user-images.githubusercontent.com/99724749/204253310-ae4594e5-f7c9-4764-826c-35934d3a54f5.png)

**Comment by allada** [comment]
Please use latest version of the file, the location was moved.

**Comment by calmbeing** [comment]
> 2\. aws s3 --request-payer=requester sync s3://public-blockchain-snapshots/bsc/erigon/archive/latest/v1/snapshots/ ./test

Doesn't it s3://public-blockchain-snapshots/bsc/erigon/archive/latest/v1/snapshots/  ?
