### ISSUE TITLE
Current version failure to download/run...

### ISSUE THREAD

**Issue by allada** [allada/bsc-archive-snapshot#45]
This is a known issue and a rebuild is in progress. It will likely take over a week to process as the last backup is from July

**Comment by calmbeing** [comment]
Hi allada, I downloaded the bsc mdbx chaindata from the sh script as in this repo, and restart the erigon for bsc archive, but stuck at 23422481 and keep showing `[2/16 Headers] No block headers to write in this log period block number=23422481`. Seemed the community encounter this problem recently but no conclusion yet
 `./build/bin/erigon --chain bsc --datadir=/server/home/qa/eri/erigon/data`
<img width="1025" alt="image" src="https://user-images.githubusercontent.com/99724749/206170383-1086111c-31be-44e7-ad47-bb319896634e.png">
