### ISSUE TITLE
S3 folder structure possibly wrong

### ISSUE THREAD

**Issue by muratso** [allada/bsc-archive-snapshot#50]
Hey, @allada thanks for your excellent work on this repo.
I've been using the GETH client for quite a long time, and it becomes harder to maintain due to its size.
I've been running some tests with Erigon for the past week and I need a full archival node with the whole chain data since the genesis block, and I thought about using your snapshot to speed thing up. However, I noticed something "wrong" with the s3 folder structure or maybe I'm misunderstanding something.

Within the `s3://public-blockchain-snapshots/bsc/erigon/archive/latest/v1/nodes/` there are like 19 levels of `/nodes` under it. Is this really expected? I mean, there's like `s3://public-blockchain-snapshots/bsc/erigon/archive/latest/v1/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/nodes/`.

**Comment by allada** [comment]
Yeah that's an error. But the nodes database is not required, it only holds info about previously connected clients and ip info.

-------- Original Message --------

**Comment by muratso** [comment]
Hmmm. So in this case, if I want to build a node from scratch, the only things I'd need to make good use of this snapshot are the `/snapshots`, `parlia`, and `chaindata` dirs?

**Comment by allada** [comment]
Exactly... The node directory is only to make resuming a sync slightly faster, so it doesn't need to spend as much time finding nodes.

-------- Original Message --------

**Comment by muratso** [comment]
Awesome. Thank you!
