### ISSUE TITLE
is it possible to split the archive over multiple servers?

### ISSUE THREAD

**Issue by cventastic** [allada/bsc-archive-snapshot#7]
Hello,

i like this repository. i have a two questions for now.

1) Is it possible to run the split archives on different servers with 1 TB storage each? 
2) I would like to see the code for ENTRY_POINT="/geth/readonly.sh" and ENTRY_POINT="/geth/latest.sh", since i dont really know how to run geth so it doesnt sync anymore.

**Comment by allada** [comment]
Those files are auto downloaded in the shell script but stored in s3
instead of GitHub because I was too lazy to rewrite the code.

If you read the script you can manually download the `geth` tarball and
extract it to get the files.

**Comment by allada** [comment]
And yes and no to your first question.

Yes you can run different parts on different nodes.

No, currently you need a little over 2tb per node. This is because the
chain is ~700gb for a fully pruned full node, so i have been splitting it
at ~2tb.
