### ISSUE TITLE
Hole in the blockchain

### ISSUE THREAD

**Issue by Denis-score** [allada/bsc-archive-snapshot#9]
Hello,

There is a little issue on the blockchain ranges provided. 

As you can see here : 

```
2021-09-07 18:10:29 1979381495977 10087707-10632706.tar.zstd
2021-10-09 17:19:21 2108037859898 10632717-11354478.tar.zstd
```

There is 11 blocks missing. We managed to correct that, by running the "10087707-10632706" node with the latest.toml file, in order to restart the synchronisation during some minutes, and recover the block missing. 

Regards

**Comment by allada** [comment]
Thanks, I have fixed it.
